builds:
  - binary: pswt
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: pswt
    homepage: https://github.com/devmegablaster/pastewut-cli/
    tap:
      owner: devmegablaster
      name: homebrew-pswt
      branch: main
    commit_author:
      name: devmegablaster
      email: devmegablaster@gmail.com

checksum:
  name_template: "checksums.txt"
