builds:
  - goos:
      - darwin
      - linux
    binary: pswt
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

brews:
  - name: pswt
    homepage: https://github.com/devmegablaster/pastewut-cli/
    tap:
      owner: devmegablaster
      name: homebrew-devmegablaster
      branch: main
    commit_author:
      name: devmegablaster
      email: devmegablaster@gmail.com

checksum:
  name_template: "checksums.txt"
